<template>
  <div>
    <scroll class="content">
      <ul>
        <li>个人列表1</li>
        <li>个人列表2</li>
        <li>个人列表3</li>
        <li>个人列表4</li>
        <li>个人列表5</li>
        <li>个人列表6</li>
        <li>个人列表7</li>
        <li>个人列表8</li>
        <li>个人列表9</li>
        <li>个人列表10</li>
        <li>个人列表11</li>
        <li>个人列表12</li>
        <li>个人列表13</li>
        <li>个人列表14</li>
        <li>个人列表15</li>
        <li>个人列表16</li>
        <li>个人列表17</li>
        <li>个人列表18</li>
        <li>个人列表19</li>
        <li>个人列表20</li>
        <li>个人列表21</li>
        <li>个人列表22</li>
        <li>个人列表23</li>
        <li>个人列表24</li>
        <li>个人列表25</li>
        <li>个人列表26</li>
        <li>个人列表27</li>
        <li>个人列表28</li>
        <li>个人列表29</li>
        <li>个人列表30</li>
        <li>个人列表31</li>
        <li>个人列表32</li>
        <li>个人列表33</li>
        <li>个人列表34</li>
        <li>个人列表35</li>
        <li>个人列表36</li>
        <li>个人列表37</li>
        <li>个人列表38</li>
        <li>个人列表39</li>
        <li>个人列表40</li>
        <li>个人列表41</li>
        <li>个人列表42</li>
        <li>个人列表43</li>
        <li>个人列表44</li>
        <li>个人列表45</li>
        <li>个人列表46</li>
        <li>个人列表47</li>
        <li>个人列表48</li>
        <li>个人列表49</li>
        <li>个人列表50</li>
        <li>个人列表51</li>
        <li>个人列表52</li>
        <li>个人列表53</li>
        <li>个人列表54</li>
        <li>个人列表55</li>
        <li>个人列表56</li>
        <li>个人列表57</li>
        <li>个人列表58</li>
        <li>个人列表59</li>
        <li>个人列表60</li>
        <li>个人列表61</li>
        <li>个人列表62</li>
        <li>个人列表63</li>
        <li>个人列表64</li>
        <li>个人列表65</li>
        <li>个人列表66</li>
        <li>个人列表67</li>
        <li>个人列表68</li>
        <li>个人列表69</li>
        <li>个人列表70</li>
        <li>个人列表71</li>
        <li>个人列表72</li>
        <li>个人列表73</li>
        <li>个人列表74</li>
        <li>个人列表75</li>
        <li>个人列表76</li>
        <li>个人列表77</li>
        <li>个人列表78</li>
        <li>个人列表79</li>
        <li>个人列表80</li>
        <li>个人列表81</li>
        <li>个人列表82</li>
        <li>个人列表83</li>
        <li>个人列表84</li>
        <li>个人列表85</li>
        <li>个人列表86</li>
        <li>个人列表87</li>
        <li>个人列表88</li>
        <li>个人列表89</li>
        <li>个人列表90</li>
        <li>个人列表91</li>
        <li>个人列表92</li>
        <li>个人列表93</li>
        <li>个人列表94</li>
        <li>个人列表95</li>
        <li>个人列表96</li>
        <li>个人列表97</li>
        <li>个人列表98</li>
        <li>个人列表99</li>
        <li>个人列表100</li>
      </ul>
    </scroll>
  </div>
</template>

<script>
import Scroll from 'components/common/scroll/Scroll'
export default {
  name:'Profile',
  components:{
    Scroll
  },
  data(){
    return{
    }
  }
}

</script>
<style scoped>
.content{
  height:500px;
  background-color:pink;
  overflow: hidden;
}
</style>